/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MembersRouteImport } from './routes/members'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CapabilityRouteImport } from './routes/capability'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityRoute = CapabilityRouteImport.update({
  id: '/capability',
  path: '/capability',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capability': typeof CapabilityRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/esg': typeof EsgRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/sectors': typeof SectorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capability': typeof CapabilityRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/esg': typeof EsgRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/sectors': typeof SectorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capability': typeof CapabilityRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/esg': typeof EsgRoute
  '/members': typeof MembersRoute
  '/news': typeof NewsRoute
  '/sectors': typeof SectorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capability'
    | '/careers'
    | '/contact'
    | '/esg'
    | '/members'
    | '/news'
    | '/sectors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capability'
    | '/careers'
    | '/contact'
    | '/esg'
    | '/members'
    | '/news'
    | '/sectors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capability'
    | '/careers'
    | '/contact'
    | '/esg'
    | '/members'
    | '/news'
    | '/sectors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CapabilityRoute: typeof CapabilityRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EsgRoute: typeof EsgRoute
  MembersRoute: typeof MembersRoute
  NewsRoute: typeof NewsRoute
  SectorsRoute: typeof SectorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability': {
      id: '/capability'
      path: '/capability'
      fullPath: '/capability'
      preLoaderRoute: typeof CapabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CapabilityRoute: CapabilityRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EsgRoute: EsgRoute,
  MembersRoute: MembersRoute,
  NewsRoute: NewsRoute,
  SectorsRoute: SectorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
